### ISSUE TITLE
go run main无法运行

### ISSUE THREAD

**Issue by guoyun911** [WeixinCloud/wxcloudrun-wxcomponent#36]
您好，我打包下载代码后，将其复制到我的服务器中，并安装了golang，按照readme中将.env.example 重命名为.env，并填入了有效参数，但是运行命令go run main 后，光标卡在换行处，一直不动

**Comment by guoyun911** [comment]
自行解决了运行问题：
1、README中说明go run main 不行，在我的环境中需要将扩展名写全，go run main.go
2、数据库wxcomponent需要手动创建，创建后才能运行go run main.go，否则报错找不到数据库
3、需要安装nodejs，并且在client/html/下运行npm install 以及npm run build，否则提示dist/index.html找不到
4、根据日志打印看出由于80端口被占用，则监听了8081端口；配置相应的nginx转发规则后，浏览器中输入地址后报404，输入/index.html也同样404，没头绪中...

以上内容未在README中体现，希望更新至README文档中，以便后面来的朋友运行顺利
问题4望wx方技术大佬指点，难道还需要配置其他什么？继续学习微信第三方文档ing

**Comment by guoyun911** [comment]
后续：
由于后台运行该服务，该服务也会把日志直接输出到终端界面，太霸道了。。看到有dockfile，就考虑用docker的方式部署，这里记录一点细节，供后面的朋友方便
1、.env文件配置的数据库配置在容器中读取不到，docker运行后会发现连接数据库失败，容器中连接的数据库地址是127.0.0.1，而我在.env中已经改了相应的数据库容器IP了；代码中看到是获取环境变量的方式来读取配置，所以我这里修改dockfile，将数据库配置写到dockfile里面（当然也可以使用docker-compose的方式，写在docker-compose文件中，运行时加载环境变量，再或者直接在docker run 加参数...不再敖述）；
2、dockerfile中使用的是npm安装前端依赖并打包，我服务器上已经安装过cnpm并已经安装依赖并打包出dist目录，所以修改了dockfile中的内容，将npm install那行注释掉了（其实也可以修改去掉nodejs的镜像依赖，需要修改下面的复制逻辑），不注释掉的话npm install会非常的慢（笔者就是等了5分钟没耐心了除此下策）。当然，也可以修改dockerfile去安装cnpm，其他方法自行发挥吧，继续探索了，good luck

**Comment by Axm11** [comment]
哥你真强，搞得我都不好意思白嫖问题处理了
